version: '3.1'
services:
  api-gateway:
    image: ilussencio/api-gateway:latest
    container_name: api-gateway
    environment:
      - DEFAULTZONE_EUREKA_CONNECTION=http://eurekaserver:8761/eureka
    ports:
      - "8765:8765"
    networks:
      - network_bridge
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log/mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/var/log/mongodb/mongod.log --logappend --bind_ip_all
    networks:
      - network_bridge
  eurekaserver:
    image: ilussencio/eureka-server:latest
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
        - network_bridge
  sonar-repositories:
    image: ilussencio/sonar-repository:latest
    environment:
      - URI_DATABASE_CONNECTION=mongodb://mongodb
      - DEFAULTZONE_EUREKA_CONNECTION=http://eurekaserver:8761/eureka
    deploy:
      replicas: 3
    networks:
      - network_bridge
networks:
  network_bridge:
    driver: bridge
